=== baiyun689/Codeguard/services/agent/evals/dataset/repo/representative-multi-v1/cases/gitbug-jaxb-uppercase/repo/src/test/resources/com/sun/tools/xjc/addon/xew/element-with-parent.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
	jaxb:version="3.0"
	jaxb:extensionBindingPrefixes="xjc"
	xmlns:jaxb="https://jakarta.ee/xml/ns/jaxb"
	xmlns:xjc="http://java.sun.com/xml/ns/jaxb/xjc"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified"
>
	<xsd:annotation>
		<xsd:appinfo>
			<jaxb:schemaBindings>
				<jaxb:package name="element_with_parent" />
			</jaxb:schemaBindings>
			<jaxb:globalBindings>
				<xjc:superClass name="com.sun.tools.xjc.addon.xew.CommonBean" />
				<xjc:serializable uid="1" />
			</jaxb:globalBindings>
		</xsd:appinfo>
	</xsd:annotation>

	<!--
		This class is not considered as candidate because it has a child class.
	-->
	<xsd:complexType name="group">
		<xsd:sequence>
			<xsd:element name="person" maxOccurs="unbounded">
				<xsd:complexType>
					<xsd:all>
						<xsd:element name="first-name" type="xsd:string" />
						<xsd:element name="second-name" type="xsd:string" />
					</xsd:all>
				</xsd:complexType>
			</xsd:element>
		</xsd:sequence>
	</xsd:complexType>

	<!--
		This class is not considered as candidate because it extends another class.
	-->
	<xsd:complexType name="organization">
		<xsd:complexContent>
			<xsd:extension base="group">
				<xsd:sequence>
					<xsd:element name="address" type="xsd:string" maxOccurs="unbounded" />
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>

	<xsd:element name="alliance">
		<xsd:complexType>
			<xsd:choice maxOccurs="unbounded">
				<xsd:element name="organization" type="organization" />
				<xsd:element name="group" type="group" />
			</xsd:choice>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== baiyun689/Codeguard/services/agent/evals/dataset/repo/representative-multi-v1/cases/gitbug-jaxb-uppercase/repo/src/test/resources/com/sun/tools/xjc/addon/xew/element-with-parent.xml
<?xml version="1.0" encoding="UTF-8"?>

<alliance xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="element-with-parent.xsd">
	<organization>
		<person>
			<first-name>Bill</first-name>
			<second-name>Smith</second-name>
		</person>
		<person>
			<first-name>Anthony</first-name>
			<second-name>Williams</second-name>
		</person>
		<address>Hall avenue 12, New York</address>
	</organization>
	<group>
		<person>
			<first-name>Sandy</first-name>
			<second-name>Morth</second-name>
		</person>
		<person>
			<first-name>Jim</first-name>
			<second-name>Simpson</second-name>
		</person>
		<person>
			<first-name>Larry</first-name>
			<second-name>Hook</second-name>
		</person>
	</group>
	<organization>
		<person>
			<first-name>Tom</first-name>
			<second-name>Sayer</second-name>
		</person>
		<address>Station street 10, New Jersey</address>
	</organization>
</alliance>
